name: Publish

on:
  push:
    branches:
      - '!*'
    tags:
      - 'v*'

permissions:
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0
      - name: Build
        run: |
          yarn install --frozen-lockfile
          ./scripts/build.sh
      - name: Publish
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./pkg
          access: public
          provenance: true
      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.BOT_TOKEN }}
          prerelease: false
